//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDTERest.wsSAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA")]
    public interface Z_BNMC_MM_RECEPCION_DTE_ACEPTA {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZBnmcMmRecepcionDteAcepta no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse1 ZBnmcMmRecepcionDteAcepta(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse1> ZBnmcMmRecepcionDteAceptaAsync(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZBnmcMmRecepcionDteAcepta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iActecoField;
        
        private string iCiudadrecepField;
        
        private string iCmnaorigenField;
        
        private string iCmnarecepField;
        
        private string iCuidadorigenField;
        
        private string iDirrecepField;
        
        private string iFchemisField;
        
        private string iFolioField;
        
        private string iGiroemisField;
        
        private string iGirorecepField;
        
        private string iIvaField;
        
        private string iMntexeField;
        
        private string iMntnetoField;
        
        private string iMnttotalField;
        
        private string iMontoimpField;
        
        private string iRutemisorField;
        
        private string iRutrecepField;
        
        private string iRznsocField;
        
        private string iRznsocrecepField;
        
        private string iTasaimpField;
        
        private string iTasaivaField;
        
        private string iTipodteField;
        
        private string iTipoimpField;
        
        private string iUriField;
        
        private ZebmncDetalleDte[] tDetalleField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IActeco {
            get {
                return this.iActecoField;
            }
            set {
                this.iActecoField = value;
                this.RaisePropertyChanged("IActeco");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ICiudadrecep {
            get {
                return this.iCiudadrecepField;
            }
            set {
                this.iCiudadrecepField = value;
                this.RaisePropertyChanged("ICiudadrecep");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ICmnaorigen {
            get {
                return this.iCmnaorigenField;
            }
            set {
                this.iCmnaorigenField = value;
                this.RaisePropertyChanged("ICmnaorigen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ICmnarecep {
            get {
                return this.iCmnarecepField;
            }
            set {
                this.iCmnarecepField = value;
                this.RaisePropertyChanged("ICmnarecep");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ICuidadorigen {
            get {
                return this.iCuidadorigenField;
            }
            set {
                this.iCuidadorigenField = value;
                this.RaisePropertyChanged("ICuidadorigen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string IDirrecep {
            get {
                return this.iDirrecepField;
            }
            set {
                this.iDirrecepField = value;
                this.RaisePropertyChanged("IDirrecep");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string IFchemis {
            get {
                return this.iFchemisField;
            }
            set {
                this.iFchemisField = value;
                this.RaisePropertyChanged("IFchemis");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IFolio {
            get {
                return this.iFolioField;
            }
            set {
                this.iFolioField = value;
                this.RaisePropertyChanged("IFolio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IGiroemis {
            get {
                return this.iGiroemisField;
            }
            set {
                this.iGiroemisField = value;
                this.RaisePropertyChanged("IGiroemis");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string IGirorecep {
            get {
                return this.iGirorecepField;
            }
            set {
                this.iGirorecepField = value;
                this.RaisePropertyChanged("IGirorecep");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string IIva {
            get {
                return this.iIvaField;
            }
            set {
                this.iIvaField = value;
                this.RaisePropertyChanged("IIva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string IMntexe {
            get {
                return this.iMntexeField;
            }
            set {
                this.iMntexeField = value;
                this.RaisePropertyChanged("IMntexe");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string IMntneto {
            get {
                return this.iMntnetoField;
            }
            set {
                this.iMntnetoField = value;
                this.RaisePropertyChanged("IMntneto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string IMnttotal {
            get {
                return this.iMnttotalField;
            }
            set {
                this.iMnttotalField = value;
                this.RaisePropertyChanged("IMnttotal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string IMontoimp {
            get {
                return this.iMontoimpField;
            }
            set {
                this.iMontoimpField = value;
                this.RaisePropertyChanged("IMontoimp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string IRutemisor {
            get {
                return this.iRutemisorField;
            }
            set {
                this.iRutemisorField = value;
                this.RaisePropertyChanged("IRutemisor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string IRutrecep {
            get {
                return this.iRutrecepField;
            }
            set {
                this.iRutrecepField = value;
                this.RaisePropertyChanged("IRutrecep");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string IRznsoc {
            get {
                return this.iRznsocField;
            }
            set {
                this.iRznsocField = value;
                this.RaisePropertyChanged("IRznsoc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string IRznsocrecep {
            get {
                return this.iRznsocrecepField;
            }
            set {
                this.iRznsocrecepField = value;
                this.RaisePropertyChanged("IRznsocrecep");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ITasaimp {
            get {
                return this.iTasaimpField;
            }
            set {
                this.iTasaimpField = value;
                this.RaisePropertyChanged("ITasaimp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ITasaiva {
            get {
                return this.iTasaivaField;
            }
            set {
                this.iTasaivaField = value;
                this.RaisePropertyChanged("ITasaiva");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string ITipodte {
            get {
                return this.iTipodteField;
            }
            set {
                this.iTipodteField = value;
                this.RaisePropertyChanged("ITipodte");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string ITipoimp {
            get {
                return this.iTipoimpField;
            }
            set {
                this.iTipoimpField = value;
                this.RaisePropertyChanged("ITipoimp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string IUri {
            get {
                return this.iUriField;
            }
            set {
                this.iUriField = value;
                this.RaisePropertyChanged("IUri");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZebmncDetalleDte[] TDetalle {
            get {
                return this.tDetalleField;
            }
            set {
                this.tDetalleField = value;
                this.RaisePropertyChanged("TDetalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZebmncDetalleDte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nrolindetField;
        
        private string tpocodigoField;
        
        private string vlrcodigoField;
        
        private string indagenteField;
        
        private string nmbitemField;
        
        private string qtyitemField;
        
        private string unmditemField;
        
        private string prcitemField;
        
        private string codimpadicField;
        
        private string montoitemField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Nrolindet {
            get {
                return this.nrolindetField;
            }
            set {
                this.nrolindetField = value;
                this.RaisePropertyChanged("Nrolindet");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Tpocodigo {
            get {
                return this.tpocodigoField;
            }
            set {
                this.tpocodigoField = value;
                this.RaisePropertyChanged("Tpocodigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vlrcodigo {
            get {
                return this.vlrcodigoField;
            }
            set {
                this.vlrcodigoField = value;
                this.RaisePropertyChanged("Vlrcodigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Indagente {
            get {
                return this.indagenteField;
            }
            set {
                this.indagenteField = value;
                this.RaisePropertyChanged("Indagente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Nmbitem {
            get {
                return this.nmbitemField;
            }
            set {
                this.nmbitemField = value;
                this.RaisePropertyChanged("Nmbitem");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Qtyitem {
            get {
                return this.qtyitemField;
            }
            set {
                this.qtyitemField = value;
                this.RaisePropertyChanged("Qtyitem");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Unmditem {
            get {
                return this.unmditemField;
            }
            set {
                this.unmditemField = value;
                this.RaisePropertyChanged("Unmditem");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Prcitem {
            get {
                return this.prcitemField;
            }
            set {
                this.prcitemField = value;
                this.RaisePropertyChanged("Prcitem");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Codimpadic {
            get {
                return this.codimpadicField;
            }
            set {
                this.codimpadicField = value;
                this.RaisePropertyChanged("Codimpadic");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Montoitem {
            get {
                return this.montoitemField;
            }
            set {
                this.montoitemField = value;
                this.RaisePropertyChanged("Montoitem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZBnmcMmRecepcionDteAceptaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eCoderrorField;
        
        private string eMsgerrorField;
        
        private string eRutaPdfField;
        
        private ZebmncDetalleDte[] tDetalleField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ECoderror {
            get {
                return this.eCoderrorField;
            }
            set {
                this.eCoderrorField = value;
                this.RaisePropertyChanged("ECoderror");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string EMsgerror {
            get {
                return this.eMsgerrorField;
            }
            set {
                this.eMsgerrorField = value;
                this.RaisePropertyChanged("EMsgerror");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ERutaPdf {
            get {
                return this.eRutaPdfField;
            }
            set {
                this.eRutaPdfField = value;
                this.RaisePropertyChanged("ERutaPdf");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZebmncDetalleDte[] TDetalle {
            get {
                return this.tDetalleField;
            }
            set {
                this.tDetalleField = value;
                this.RaisePropertyChanged("TDetalle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZBnmcMmRecepcionDteAceptaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public APIDTERest.wsSAP.ZBnmcMmRecepcionDteAcepta ZBnmcMmRecepcionDteAcepta;
        
        public ZBnmcMmRecepcionDteAceptaRequest() {
        }
        
        public ZBnmcMmRecepcionDteAceptaRequest(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAcepta ZBnmcMmRecepcionDteAcepta) {
            this.ZBnmcMmRecepcionDteAcepta = ZBnmcMmRecepcionDteAcepta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZBnmcMmRecepcionDteAceptaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse ZBnmcMmRecepcionDteAceptaResponse;
        
        public ZBnmcMmRecepcionDteAceptaResponse1() {
        }
        
        public ZBnmcMmRecepcionDteAceptaResponse1(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse ZBnmcMmRecepcionDteAceptaResponse) {
            this.ZBnmcMmRecepcionDteAceptaResponse = ZBnmcMmRecepcionDteAceptaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_BNMC_MM_RECEPCION_DTE_ACEPTAChannel : APIDTERest.wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_BNMC_MM_RECEPCION_DTE_ACEPTAClient : System.ServiceModel.ClientBase<APIDTERest.wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA>, APIDTERest.wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA {
        
        public Z_BNMC_MM_RECEPCION_DTE_ACEPTAClient() {
        }
        
        public Z_BNMC_MM_RECEPCION_DTE_ACEPTAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_BNMC_MM_RECEPCION_DTE_ACEPTAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_BNMC_MM_RECEPCION_DTE_ACEPTAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_BNMC_MM_RECEPCION_DTE_ACEPTAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse1 APIDTERest.wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA.ZBnmcMmRecepcionDteAcepta(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest request) {
            return base.Channel.ZBnmcMmRecepcionDteAcepta(request);
        }
        
        public APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse ZBnmcMmRecepcionDteAcepta(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAcepta ZBnmcMmRecepcionDteAcepta1) {
            APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest inValue = new APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest();
            inValue.ZBnmcMmRecepcionDteAcepta = ZBnmcMmRecepcionDteAcepta1;
            APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse1 retVal = ((APIDTERest.wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA)(this)).ZBnmcMmRecepcionDteAcepta(inValue);
            return retVal.ZBnmcMmRecepcionDteAceptaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse1> APIDTERest.wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA.ZBnmcMmRecepcionDteAceptaAsync(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest request) {
            return base.Channel.ZBnmcMmRecepcionDteAceptaAsync(request);
        }
        
        public System.Threading.Tasks.Task<APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaResponse1> ZBnmcMmRecepcionDteAceptaAsync(APIDTERest.wsSAP.ZBnmcMmRecepcionDteAcepta ZBnmcMmRecepcionDteAcepta) {
            APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest inValue = new APIDTERest.wsSAP.ZBnmcMmRecepcionDteAceptaRequest();
            inValue.ZBnmcMmRecepcionDteAcepta = ZBnmcMmRecepcionDteAcepta;
            return ((APIDTERest.wsSAP.Z_BNMC_MM_RECEPCION_DTE_ACEPTA)(this)).ZBnmcMmRecepcionDteAceptaAsync(inValue);
        }
    }
}
